<?php

/**
 * @file
 * Contains terrific.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\terrific_integration\AssetManager;

/**
 * Implements hook_help().
 */
function terrific_integration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the terrific module.
    case 'help.page.terrific_integration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Terrific Integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function terrific_integration_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function terrific_integration_preprocess_page(&$variables) {
  if (\Drupal::theme()->getActiveTheme()->getName() == 'terrific') {
    $frontendBase = __DIR__ . '/../../../../../frontend/';
    $config = json_decode(file_get_contents($frontendBase . 'config.json'));
    $assetManager = new AssetManager($frontendBase);

    $mainJs = 'main.js';
    $data = $config->assets->{$mainJs};
    $assetManager->dump($data, $mainJs);

    $mainCss = 'main.css';
    $data = $config->assets->{$mainCss};
    $assetManager->dump($data, $mainCss);
  }
}

/**
 * Implements hook_js_alter().
 */
function terrific_integration_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  if (\Drupal::theme()->getActiveTheme()->getName() == 'terrific') {
    $javascript['terrific/main.js'] = [
      'data' => _terrific_integration_file_path('main.js'),
      'scope' => 'footer',
      'minified' => FALSE,
      'type' => 'file',
      'group' => -150,
      'weight' => 0,
      'browsers' => array(),
      'cache' => TRUE,
      'version' => '1.0.0',
    ];
  }
}

/**
 * Implements hook_css_alter().
 */
function terrific_integration_css_alter(&$css, AttachedAssetsInterface $assets) {
  if (\Drupal::theme()->getActiveTheme()->getName() == 'terrific') {
    $css['terrific/main.css'] = [
      'data' => _terrific_integration_file_path('main.css'),
      'type' => 'file',
      'group' => -150,
      'weight' => 0,
      'browsers' => array(),
      'media' => 'all',
      'preprocess' => FALSE,
      'version' => '1.0.0',
    ];
  }
}

/**
 * Implements hook_cache_flush().
 */
function terrific_integration_cache_flush() {
  $files = glob(\Drupal::service('file_system')->realpath('public://terrific') . '/*');
  foreach ($files as $file) {
    if (is_file($file)) {
      unlink($file);
    }
  }
}

/**
 * Helper function to return the path of the asset.
 */
function _terrific_integration_file_path($assetName) {
  return '/sites/default/files/terrific/' . \Drupal::state()->get('system.css_js_query_string') . '-' . $assetName;
}
