<?php

/**
 * @file
 * Contains terrific.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\terrific_integration\AssetManager;

/**
 * Implements hook_help().
 */
function terrific_integration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the terrific module.
    case 'help.page.terrific_integration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Terrific Integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_rebuild().
 */
function terrific_integration_rebuild() {
  $frontendBase = __DIR__ . '/../../../../../frontend/';
  $jsFiles = ['head.js', 'app.js', 'main.js'];
  $cssFiles = ['main.css', 'app.css'];

  $config = json_decode(file_get_contents($frontendBase . 'config.json'));
  $assetManager = new AssetManager($frontendBase);
  foreach ($config->assets as $key => $conf) {
    if (in_array($key, $jsFiles) || in_array($key, $cssFiles)) {
      $data = $config->assets->{$key};
      $assetManager->dump($data, $key);
    }
  }
}
